use_frameworks!

install! 'cocoapods', :deterministic_uuids => false

target 'lottie-swift_macOS' do
  platform :osx, '12'
  pod 'lottie-ios', :git => 'https://github.com/Aktivolabs/lottie-ios.git', :branch => 'main'
end

target 'lottie-swift_tvOS' do
  platform :tvos, '12'
  pod 'lottie-ios', :git => 'https://github.com/Aktivolabs/lottie-ios.git', :branch => 'main'
end

target 'lottie-swift_Example' do
  platform :ios, '12'
  pod 'lottie-ios', :git => 'https://github.com/Aktivolabs/lottie-ios.git', :branch => 'main'

  target 'lottie-swift_Tests' do
    inherit! :search_paths
  end
end